import { useState } from "react";
import {
  Card,
  CardHeader,
  CardTitle,
  CardContent,
  CardDescription,
} from "./ui/card";
import { Sparkles, User, Bot, Send } from "lucide-react";
import { ScrollArea } from "./ui/scroll-area";
import { Avatar, AvatarFallback } from "./ui/avatar";
import { Button } from "./ui/button";
import { Textarea } from "./ui/textarea";
import ReactMarkdown from 'react-markdown';
import { useRef, useEffect } from 'react';

//interface for chat panel component
interface Message {
  id: number;
  role: "user" | "assistant";
  content: string;
  timestamp: Date;
}

//chat panel props
interface ChatPanelProps {
  onNavigate: (page: string) => void;
}

const initialMessages: Message[] = [
  {
    id: 1,
    role: "assistant",
    content:
      "Hi! My name is Gabina, I'm your AI financial assistant. I can help you understand your spending, suggest savings strategies, and answer questions about your finances. How can I help you today?",
    timestamp: new Date(),
  },
];

//sample questions for user to ask
const sampleQuestions = [
  "How can I reduce my spending?",
  "What's my biggest expense?",
  "What's my lowest expense?",
  "Show me dining trends",
];

//initial messages for chat panel
export function ChatPanel({}: ChatPanelProps) {
  //state definitions
  const [messages, setMessages] = useState<Message[]>(initialMessages);
  const [input, setInput] = useState("");
  const [isTyping, setIsTyping] = useState(false);

  //The Auto-Scroll Anchor
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const handleSend = async () => {
    if (!input.trim()) return;

    //update messages with user input
    // 1. Instantly put the User's message on the screen
    const userMessage: Message = {
      id: messages.length + 1,
      role: "user",
      content: input,
      timestamp: new Date(),
    };
    //update messages state
    // Add it to the array while keeping the old messages
    setMessages((prevMessages) => [...prevMessages, userMessage]);
    setInput(""); // Clear the input box

    try {
      // 2. Send JUST this new message to your backend API
      const response = await fetch("http://localhost:8000/api/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        // We package the text into a tiny JSON envelope to send it over
        body: JSON.stringify({ question: userMessage.content }),
      });

      const data = await response.json();

      // 3. The backend replies with JSON containing the AI's answer!
      const assistantMessage: Message = {
        id: messages.length + 2,
        role: "assistant",
        content: data.answer, // The text generated by your Python LLM
        timestamp: new Date(),
      };

      // 4. Add the AI's message to the screen
      setMessages((prevMessages) => [...prevMessages, assistantMessage]);
    } catch (error) {
      console.error("Chat API broke:", error);
    }
  };

  const handleQuestionClick = (question: string) => {
    setInput(question);
  };

  //Automatically scroll down whenever the 'messages' array changes
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, isTyping]);

  return (
    // Chat Panel Card
    <Card className="h-[600px] lg:sticky lg:top-24 flex flex-col">
      {/* Card Header with Title and Description */}
      <CardHeader className="border-b">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-gradient-to-br from-emerald-600 to-teal-600 rounded-full flex items-center justify-center">
            <Sparkles className="w-5 h-5 text-white" />
          </div>
          <div>
            <CardTitle>Gabina</CardTitle>
            <CardDescription>
              Ask me anything about your finances
            </CardDescription>
          </div>
        </div>
      </CardHeader>

      {/* Card Content with Messages */}
      <CardContent className="flex-1 flex flex-col p-0 overflow-hidden">
        <ScrollArea className="flex-1 p-4">
          <div className="space-y-4">
            
            {/* Render each message */}
            {messages.map((message) => (
              // Individual Message Container
              <div
                key={message.id}
                className={`flex gap-3 w-full ${message.role === "user" ? "flex-row-reverse" : ""}`}
              >
                {/* Avatar for User or Assistant */}
                <Avatar
                  className={`w-8 h-8 flex-shrink-0 ${message.role === "assistant" ? "bg-emerald-100" : "bg-gray-100"}`}
                >
                  <AvatarFallback>
                    {message.role === "assistant" ? (
                      <Bot className="w-4 h-4 text-emerald-600" />
                    ) : (
                      <User className="w-4 h-4 text-gray-600" />
                    )}
                  </AvatarFallback>
                </Avatar>

                {/* UPGRADED Message Bubble: max-w-[80%], break-words, and overflow-hidden */}
                <div
                  className={`rounded-lg p-3 max-w-[80%] break-words overflow-hidden ${
                    message.role === "user"
                      ? "bg-emerald-600 text-white"
                      : "bg-gray-100 text-gray-900"
                  }`}
                >
                  {/* THE TEXT FIX: ReactMarkdown for AI, standard pre-wrap for User */}
                  {message.role === "assistant" ? (
                    <div className="prose prose-sm max-w-none text-gray-900 prose-p:leading-relaxed prose-pre:bg-gray-200">
                      <ReactMarkdown>{message.content}</ReactMarkdown>
                    </div>
                  ) : (
                    <p className="text-sm whitespace-pre-wrap">
                      {message.content}
                    </p>
                  )}
                </div>
              </div>
            ))}

            {/* Typing Indicator */}
            {isTyping && (
              <div className="flex gap-3">
                <Avatar className="w-8 h-8 flex-shrink-0 bg-emerald-100">
                  <AvatarFallback>
                    <Bot className="w-4 h-4 text-emerald-600" />
                  </AvatarFallback>
                </Avatar>
                <div className="bg-gray-100 rounded-lg p-4">
                  <div className="flex gap-1">
                    <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: "0ms" }}></div>
                    <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: "150ms" }}></div>
                    <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: "300ms" }}></div>
                  </div>
                </div>
              </div>
            )}
            
            {/* Auto-Scroll Anchor: This invisible div acts as the target for our scroller */}
            <div ref={messagesEndRef} />

          </div>
        </ScrollArea>

        {/* Input suggestion area for user  */}
        {messages.length === 1 && (
          <div className="p-4 border-t bg-gray-50">
            <p className="text-xs text-gray-600 mb-2">Try asking:</p>
            <div className="flex flex-wrap gap-2">
              {sampleQuestions.map((question, index) => (
                <Button
                  key={index}
                  variant="outline"
                  size="sm"
                  className="text-xs"
                  onClick={() => handleQuestionClick(question)}
                >
                  {question}
                </Button>
              ))}
            </div>
          </div>
        )}

        {/* input area for user to type questions */}
        <div className="p-4 border-t bg-white">
          <div className="flex gap-2">
            <Textarea
              placeholder="Ask about your spending, savings, or goals..."
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter" && !e.shiftKey) {
                  e.preventDefault();
                  handleSend();
                }
              }}
              className="min-h-[60px] resize-none"
            />
            <Button
              onClick={handleSend}
              disabled={!input.trim() || isTyping}
              className="self-end bg-emerald-600 hover:bg-emerald-700"
            >
              <Send className="w-4 h-4" />
            </Button>
          </div>
          <p className="text-xs text-gray-500 mt-2">
            Press Enter to send, Shift+Enter for new line
          </p>
        </div>
      </CardContent>
    </Card>
  );
}
